version: '3'

services:
  slides:
    build:
      context: .
      target: builder
    command: npm start
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - build:/app/build
      - node_modules:/app/node_modules
volumes:
  build:
  node_modules:
